version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
  social:
    build: ./src/Backend/Neo4j
    ports:
      - "81:81"
  firebase:
    build: ./src/Backend/Firebase
    ports:
      - "80:80"
  search:
    build: ./src/Backend/Elasticsearch
    ports:
      - "82:82"
  notifications:
    build: ./src/Backend/RabbitMQ
    ports:
      - "5555:5555"
  indicization:
    build: ./src/Backend/Indices
    ports:
      - "83:83"
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: es01
      discovery.seed_hosts: es01
      cluster.initial_master_nodes: es01
      cluster.name: mycluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    depends_on:
      es01:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200"]'

  kong:
    container_name: kong-dbless
    image: kong/kong-gateway:3.1.1.1
    environment:
      - KONG_DATABASE=off
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_LICENSE_DATA
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
    volumes:
      - "./:/kong/declarative/"
  deepdetect:
    image: docker.jolibrain.com/deepdetect_cpu
    ports:
      - "8080:8080"

volumes:
  es-data-es01:
